### ISSUE TITLE
Darktable  2.4.1 started with squareboxes (charset/font issue)

### ISSUE THREAD

**Issue by glazeus** [kyrofa/darktable-snap#10]
cat /etc/os-release 
>PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

snap --version
>snap    2.32.5
snapd   2.32.5
series  16
debian  9
kernel  4.9.0-6-amd64

gnome-shell --version
>GNOME Shell 3.22.3

darktable-kyrofa.darktable --version
>this is darktable 2.4.1
copyright (c) 2009-2018 johannes hanika
darktable-dev@lists.darktable.org
compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support disabled
  Colord support disabled
  gPhoto2 support disabled
  GraphicsMagick support enabled
  OpenEXR support enabled

darktable-kyrofa.darktable all
![darktable-kyrofa.darktable all](https://user-images.githubusercontent.com/25101823/39428782-ee194de6-4c88-11e8-93b1-f07e556164b7.png)

Please advise how it possible to fix.

Thank you

**Comment by kyrofa** [comment]
Huh... no idea what's happening here. I'll see if I can get some time to get a Debian VM up and test it.

**Comment by glazeus** [comment]
UPDATE:
looks issue was gone after in version `2.4.1`
Current version is working as expected
>darktable-kyrofa.darktable --version
this is darktable 2.4.3
