### ISSUE TITLE
Lua scripts aren't usable 

### ISSUE THREAD

**Issue by wpferguson** [kyrofa/darktable-snap#11]
Darktable is extensible using the lua scripting language.  There is a repository of scripts at https://github.com/darktable-org/lua-scripts that are intended for use with darktable.  Unfortunately these don't work with the snap packaged darktable.  One solution is to enable the internal lua interpreter (CMakeLists.txt DONT_USE_INTERNAL_LUA OFF). Another is to let darktable bind at run time with the lua library installed on the operating system (Ubuntu 16.04 - /usr/lib/x86_64-linux-gnu/liblua5.3.so.0).  A third is bundle lua5.3 with darktable in the snap package.

**Comment by wpferguson** [comment]
Thanks

**Comment by kyrofa** [comment]
This is fixed in the `edge` channel, and will be officially released in `2.4.3snap2`.

**Comment by kyrofa** [comment]
Note that this has now been released to stable.
