### ISSUE TITLE
Icon SVG renders incorrectly

### ISSUE THREAD

**Issue by danrobinson78** [kyrofa/darktable-snap#21]
Installed via Snap, Darktable uses a black icon, rather than the colored one used by the .deb versions that are out there (either native Ubuntu repos or the OBS repos).
It looks like the colored icon seems to be preferred and is what's used by upstream unless I'm missing something.

**Comment by kyrofa** [comment]
Huh, this is the icon I see:

![Screenshot from 2019-11-22 12-06-47](https://user-images.githubusercontent.com/946674/69456869-a1081f00-0d20-11ea-8543-d0b0bcc0b132.png)

You're seeing a different one?

**Comment by danrobinson78** [comment]
Here's what I'm seeing. Black one is from the snap, colored one is from the upstream OBS repo.

![Screenshot from 2019-11-22 15-22-48](https://user-images.githubusercontent.com/32584841/69457853-01588a00-0d3c-11ea-91f4-92e171201ce2.png)

**Comment by kyrofa** [comment]
Hmm, might be a rendering issue. The icon being used is `/snap/darktable/current/meta/gui/icon.svg`, which for me looks like this:

![Screenshot from 2019-11-22 12-27-51](https://user-images.githubusercontent.com/946674/69458129-85524800-0d23-11ea-9601-cf907786f0a1.png)

What OS are you on?

**Comment by kyrofa** [comment]
> FWIW when I pull up the .SVG icon in this repository I do see the black icon as well.

Same here actually, when I view it in Firefox. But if I download it and open it on Ubuntu it looks fine.

**Comment by danrobinson78** [comment]
I'm on Ubuntu Eoan.

I see the SVG as black on Firefox as well, but I guess for some reason it's also showing up black on the dock.

**Comment by kyrofa** [comment]
Hmm, hey @kenvandine any chance you have a clue what's happening here? Did Eoan change how SVGs are rendered in some way?

**Comment by danrobinson78** [comment]
So what's weird is the native package does seem to also ship svg icons and they render fine.

I also vaguely remember seeing it on Disco too, I can check if needed.

**Comment by kyrofa** [comment]
To be clear, I have no problem updating the icon used here, but I'm nervous doing anything without a clear idea of what the problem actually is.

**Comment by danrobinson78** [comment]
Yeah, no argument from me on that. I just assumed it was somehow grabbing an alternate icon or something but it does seem to be somehow related to SVG rendering.

**Comment by kyrofa** [comment]
Oh and just to mention: I'm on Bionic.

**Comment by kyrofa** [comment]
Thanks again for the report @danrobinson78, this is very weird.

**Comment by danrobinson78** [comment]
Sure thing! If there's any other data I can get that would be useful let me know, I'm just not sure exactly where to start with this one.

**Comment by kenvandine** [comment]
I've confirmed the icon.svg shipped in the snap renders black even in eog on 19.10.  However inkscape renders it properly.  I tried a few svg icons from other snaps and they look fine.  Perhaps there is something about that particular svg file that is triggering a librsvg bug?

**Comment by danrobinson78** [comment]
Sorry for late reply, email threaded things weird and I didn't notice there was a change committed. Seems to be corrected on Eoan currently! Thanks everyone for the help.
