### ISSUE TITLE
2.0.7snap1 Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by pixelr0** [kyrofa/darktable-snap#3]
ubuntu 16.04, snapd 2.16ubuntu3, darktable-kyrofa   2.0.7snap1                    9    kyrofa         -

~$ darktable-kyrofa.darktable 
[defaults] found a 64-bit system with 2048112 kb ram and 2 cores (0 atom based)
[defaults] setting very conservative defaults

(process:15855): GLib-CRITICAL **: g_variant_unref: assertion 'value != NULL' failed

** (darktable:15855): WARNING **: Couldn't register with accessibility bus: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender="(null)" (inactive) interface="org.freedesktop.DBus" member="Hello" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus)

(darktable:15855): Gtk-WARNING **: Failed to parse /etc/gtk-3.0/settings.ini: Permission denied
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Illegal instruction (core dumped)

**Comment by pixelr0** [comment]
it's the same with the --candidate version

**Comment by kyrofa** [comment]
Can you please try the following:

    $ sudo snap install snappy-debug
    $ sudo snap connect snappy-debug:log-observe ubuntu-core:log-observe
    $ sudo snappy-debug.security scanlog

That will block. Open up another terminal/tab and run darktable again. Can you please paste whatever snappy-debug says in here?

**Comment by pixelr0** [comment]
sure :D

~$ snappy-debug.security scanlog
sysctl: permission denied on key 'kernel.printk_ratelimit'
= AppArmor =
Time: Nov 26 01:50:08
Log: apparmor="DENIED" operation="open" profile="snap.darktable-kyrofa.darktable" name="/etc/gtk-3.0/settings.ini" pid=16409 comm="darktable" requested_mask="r" denied_mask="r" fsuid=1001 ouid=0
File: /etc/gtk-3.0/settings.ini (read)
Suggestion:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON

= AppArmor =
Time: Nov 26 01:50:08
Log: apparmor="DENIED" operation="open" profile="snap.darktable-kyrofa.darktable" name="/usr/share/icons/hicolor/48x48/apps/" pid=16409 comm="darktable" requested_mask="r" denied_mask="r" fsuid=1001 ouid=0
File: /usr/share/icons/hicolor/48x48/apps/ (read)
Suggestion:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON

= AppArmor =
Time: Nov 26 01:50:08
Log: apparmor="DENIED" operation="open" profile="snap.darktable-kyrofa.darktable" name="/usr/share/icons/hicolor/scalable/apps/" pid=16409 comm="darktable" requested_mask="r" denied_mask="r" fsuid=1001 ouid=0
File: /usr/share/icons/hicolor/scalable/apps/ (read)
Suggestion:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON

= AppArmor =
Time: Nov 26 01:50:08
Log: apparmor="DENIED" operation="open" profile="snap.darktable-kyrofa.darktable" name="/usr/share/icons/" pid=16409 comm="darktable" requested_mask="r" denied_mask="r" fsuid=1001 ouid=0
File: /usr/share/icons/ (read)
Suggestions:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON
* add 'unity7' to 'plugs'

= AppArmor =
Time: Nov 26 01:50:08
Log: apparmor="DENIED" operation="open" profile="snap.darktable-kyrofa.darktable" name="/usr/share/pixmaps/" pid=16409 comm="darktable" requested_mask="r" denied_mask="r" fsuid=1001 ouid=0
File: /usr/share/pixmaps/ (read)
Suggestions:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON
* add 'unity7' to 'plugs'

**Comment by kyrofa** [comment]
Nothing looks suspicious there. Regardless, I've spun up builds that include the unity7 plug which should be available in about 30 minutes (2.0.7snap2 in stable, 2.2.0-rc1-snap2 in candidate)-- please try that when you can. There may be a darktable bug here. If you're comfortable [enabling core dumps](https://github.com/snapcore/snapcraft/blob/master/docs/debug.md#enabling-coredumps) I'd be curious to take a look.

**Comment by kyrofa** [comment]
Also, are you doing something specific within darktable that causes this? Or just start it and watch it die?

**Comment by pixelr0** [comment]
ok, so since i can't sleep :D 

darktable-kyrofa (stable) 2.0.7snap2 from 'kyrofa' installed
~$ darktable-kyrofa.darktable 
Illegal instruction (core dumped)

~$ snappy-debug.security scanlog
sysctl: permission denied on key 'kernel.printk_ratelimit'
= AppArmor =
Time: Nov 26 03:45:03
Log: apparmor="DENIED" operation="open" profile="snap.darktable-kyrofa.darktable" name="/usr/share/glib-2.0/schemas/" pid=4550 comm="desktop-launch" requested_mask="r" denied_mask="r" fsuid=1001 ouid=0
File: /usr/share/glib-2.0/schemas/ (read)
Suggestion:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON

i don't see nothing, it doesn't even open a window (2.0.7snap2), with 2.0.7snap1 i did see a transparent  window  for about 1 second before closing.

i also tried on 17.04/ snapd 2.18 same result :D (i do have unity8 session snap installed on 17.04)
on 16.04 i removed the session before testing again.

i've mention unity8 session snap because my unity7 session was affected by this bug https://bugs.launchpad.net/ubuntu/+source/dbus/+bug/1644323

**Comment by pixelr0** [comment]
syslog 

Nov 26 03:48:22 pixel-MS-7369 /usr/lib/snapd/snapd[862]: daemon.go:174: DEBUG: uid=1001;@ GET /v2/snaps 6.895599ms 200
Nov 26 03:48:22 pixel-MS-7369 kernel: [  925.037295] traps: darktable[4707] trap invalid opcode ip:7f1f4ec5c8e7 sp:7ffeb1cd2280 error:0 in libdarktable.so[7f1f4ebed000+24d000]
Nov 26 03:56:14 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2738 on Do: Stop snap "darktable-kyrofa" services
Nov 26 03:56:14 pixel-MS-7369 /usr/lib/snapd/snapd[862]: daemon.go:174: DEBUG: uid=1001;@ POST /v2/snaps/darktable-kyrofa 51.565382ms 202
Nov 26 03:56:14 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2739 on Do: Make snap "darktable-kyrofa" unavailable to the system
Nov 26 03:56:14 pixel-MS-7369 /usr/lib/snapd/snapd[862]: desktop.go:178: DEBUG: update-desktop-database successful
Nov 26 03:56:14 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2740 on Do: Remove security profile for snap "darktable-kyrofa" (15)
Nov 26 03:56:14 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2741 on Do: Remove data for snap "darktable-kyrofa" (15)
Nov 26 03:56:14 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2742 on Do: Remove snap "darktable-kyrofa" (15) from the system
Nov 26 03:56:14 pixel-MS-7369 systemd[1]: Unmounted Mount unit for darktable-kyrofa.
Nov 26 03:56:15 pixel-MS-7369 systemd[1]: Reloading.
Nov 26 03:56:15 pixel-MS-7369 systemd[1]: snapd.refresh.timer: Adding 3h 57min 45.861785s random time.
Nov 26 03:56:15 pixel-MS-7369 systemd[1]: apt-daily.timer: Adding 5h 9min 42.410103s random time.
Nov 26 03:56:15 pixel-MS-7369 systemd[1]: Started ACPI event daemon.
Nov 26 03:56:15 pixel-MS-7369 systemd[1]: Started CUPS Scheduler.
Nov 26 03:56:15 pixel-MS-7369 systemd[1]: Reloading.
Nov 26 03:56:15 pixel-MS-7369 systemd[1]: snapd.refresh.timer: Adding 5h 6min 7.884940s random time.
Nov 26 03:56:15 pixel-MS-7369 systemd[1]: apt-daily.timer: Adding 9h 3min 42.253314s random time.
Nov 26 03:56:15 pixel-MS-7369 systemd[1]: Started ACPI event daemon.
Nov 26 03:56:15 pixel-MS-7369 systemd[1]: Started CUPS Scheduler.
Nov 26 03:56:16 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2743 on Do: Discard interface connections for snap "darktable-kyrofa" (15)
Nov 26 03:56:17 pixel-MS-7369 gnome-session[2184]: (gnome-software:2335): Gs-WARNING **: failed to get updates: no results to show
Nov 26 03:56:28 pixel-MS-7369 /usr/lib/snapd/snapd[862]: api.go:793: Installing snap "darktable-kyrofa" revision unset
Nov 26 03:56:28 pixel-MS-7369 snapd[862]: 2016/11/26 03:56:28.971744 api.go:793: Installing snap "darktable-kyrofa" revision unset
Nov 26 03:56:29 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2744 on Do: Download snap "darktable-kyrofa" (16) from channel "candidate"
Nov 26 03:56:29 pixel-MS-7369 /usr/lib/snapd/snapd[862]: daemon.go:174: DEBUG: uid=1001;@ POST /v2/snaps/darktable-kyrofa 354.734256ms 202
Nov 26 03:56:46 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2745 on Do: Fetch and check assertions for snap "darktable-kyrofa" (16)
Nov 26 03:56:47 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2746 on Do: Mount snap "darktable-kyrofa" (16)
Nov 26 03:56:49 pixel-MS-7369 systemd[1]: Reloading.
Nov 26 03:56:49 pixel-MS-7369 systemd[1]: snapd.refresh.timer: Adding 2h 51min 17.439551s random time.
Nov 26 03:56:49 pixel-MS-7369 systemd[1]: apt-daily.timer: Adding 3h 8min 58.602485s random time.
Nov 26 03:56:49 pixel-MS-7369 systemd[1]: Started ACPI event daemon.
Nov 26 03:56:49 pixel-MS-7369 systemd[1]: Started CUPS Scheduler.
Nov 26 03:56:49 pixel-MS-7369 systemd[1]: Reloading.
Nov 26 03:56:49 pixel-MS-7369 systemd[1]: snapd.refresh.timer: Adding 2h 20min 55.273804s random time.
Nov 26 03:56:49 pixel-MS-7369 systemd[1]: apt-daily.timer: Adding 2h 36min 52.196317s random time.
Nov 26 03:56:49 pixel-MS-7369 systemd[1]: Started ACPI event daemon.
Nov 26 03:56:49 pixel-MS-7369 systemd[1]: Started CUPS Scheduler.
Nov 26 03:56:49 pixel-MS-7369 systemd[1]: Mounting Mount unit for darktable-kyrofa...
Nov 26 03:56:49 pixel-MS-7369 systemd[1]: Mounted Mount unit for darktable-kyrofa.
Nov 26 03:56:50 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2747 on Do: Copy snap "darktable-kyrofa" data
Nov 26 03:56:50 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2748 on Do: Setup snap "darktable-kyrofa" (16) security profiles
Nov 26 03:56:51 pixel-MS-7369 kernel: [ 1433.725748] audit: type=1400 audit(1480125411.061:91): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="snap.darktable-kyrofa.darktable" pid=4971 comm="apparmor_parser"
Nov 26 03:56:51 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2749 on Do: Make snap "darktable-kyrofa" (16) available to the system
Nov 26 03:56:51 pixel-MS-7369 gnome-session[2184]: (gnome-software:2335): As-WARNING **: failed to rescan: Failed to parse /var/lib/snapd/desktop/applications/darktable-kyrofa_darktable.desktop file: cannot process file of type application/x-desktop
Nov 26 03:56:51 pixel-MS-7369 /usr/lib/snapd/snapd[862]: desktop.go:178: DEBUG: update-desktop-database successful
Nov 26 03:56:51 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2750 on Do: Start snap "darktable-kyrofa" (16) services
Nov 26 03:56:51 pixel-MS-7369 /usr/lib/snapd/snapd[862]: daemon.go:174: DEBUG: uid=1001;@ GET /v2/snaps 13.963377ms 200
Nov 26 03:56:54 pixel-MS-7369 gnome-session[2184]: (gnome-software:2335): Gs-WARNING **: failed to get updates: no results to show
Nov 26 03:57:12 pixel-MS-7369 /usr/lib/snapd/snapd[862]: daemon.go:174: DEBUG: uid=1001;@ GET /v2/snaps 5.912476ms 200
Nov 26 03:57:33 pixel-MS-7369 kernel: [ 1476.643160] audit: type=1400 audit(1480125453.978:92): apparmor="DENIED" operation="open" profile="snap.darktable-kyrofa.darktable" name="/usr/share/glib-2.0/schemas/" pid=5014 comm="desktop-launch" requested_mask="r" denied_mask="r" fsuid=1001 ouid=0
Nov 26 03:57:35 pixel-MS-7369 kernel: [ 1478.597293] traps: darktable[4974] trap invalid opcode ip:7ff824f9b5bf sp:7ffd91446a80 error:0 in libdarktable.so[7ff824f1f000+276000]
Nov 26 04:02:52 pixel-MS-7369 /usr/lib/snapd/snapd[862]: daemon.go:174: DEBUG: uid=1001;@ POST /v2/snaps/darktable-kyrofa 60.398188ms 202
Nov 26 04:02:52 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2751 on Do: Stop snap "darktable-kyrofa" services
Nov 26 04:02:52 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2752 on Do: Make snap "darktable-kyrofa" unavailable to the system
Nov 26 04:02:52 pixel-MS-7369 /usr/lib/snapd/snapd[862]: desktop.go:178: DEBUG: update-desktop-database successful
Nov 26 04:02:52 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2753 on Do: Remove security profile for snap "darktable-kyrofa" (16)
Nov 26 04:02:52 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2754 on Do: Remove data for snap "darktable-kyrofa" (16)
Nov 26 04:02:52 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2755 on Do: Remove snap "darktable-kyrofa" (16) from the system
Nov 26 04:02:53 pixel-MS-7369 systemd[1]: Unmounted Mount unit for darktable-kyrofa.
Nov 26 04:02:53 pixel-MS-7369 systemd[1]: Reloading.
Nov 26 04:02:53 pixel-MS-7369 systemd[1]: snapd.refresh.timer: Adding 51min 48.411352s random time.
Nov 26 04:02:53 pixel-MS-7369 systemd[1]: apt-daily.timer: Adding 7h 43min 19.165126s random time.
Nov 26 04:02:53 pixel-MS-7369 systemd[1]: Started ACPI event daemon.
Nov 26 04:02:53 pixel-MS-7369 systemd[1]: Started CUPS Scheduler.
Nov 26 04:02:53 pixel-MS-7369 systemd[1]: Reloading.
Nov 26 04:02:54 pixel-MS-7369 systemd[1]: snapd.refresh.timer: Adding 1h 30min 4.521847s random time.
Nov 26 04:02:54 pixel-MS-7369 systemd[1]: apt-daily.timer: Adding 6h 20min 45.851544s random time.
Nov 26 04:02:54 pixel-MS-7369 systemd[1]: Started ACPI event daemon.
Nov 26 04:02:54 pixel-MS-7369 systemd[1]: Started CUPS Scheduler.
Nov 26 04:02:54 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2756 on Do: Discard interface connections for snap "darktable-kyrofa" (16)
Nov 26 04:02:56 pixel-MS-7369 gnome-session[2184]: (gnome-software:2335): Gs-WARNING **: failed to get updates: no results to show
Nov 26 04:03:02 pixel-MS-7369 /usr/lib/snapd/snapd[862]: api.go:793: Installing snap "darktable-kyrofa" revision unset
Nov 26 04:03:02 pixel-MS-7369 snapd[862]: 2016/11/26 04:03:02.512955 api.go:793: Installing snap "darktable-kyrofa" revision unset
Nov 26 04:03:02 pixel-MS-7369 /usr/lib/snapd/snapd[862]: daemon.go:174: DEBUG: uid=1001;@ POST /v2/snaps/darktable-kyrofa 330.6736ms 202
Nov 26 04:03:02 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2757 on Do: Download snap "darktable-kyrofa" (15) from channel "stable"
Nov 26 04:03:18 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2758 on Do: Fetch and check assertions for snap "darktable-kyrofa" (15)
Nov 26 04:03:20 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2759 on Do: Mount snap "darktable-kyrofa" (15)
Nov 26 04:03:21 pixel-MS-7369 systemd[1]: Reloading.
Nov 26 04:03:21 pixel-MS-7369 systemd[1]: snapd.refresh.timer: Adding 2h 44min 7.527889s random time.
Nov 26 04:03:21 pixel-MS-7369 systemd[1]: apt-daily.timer: Adding 5h 49min 42.138872s random time.
Nov 26 04:03:21 pixel-MS-7369 systemd[1]: Started ACPI event daemon.
Nov 26 04:03:21 pixel-MS-7369 systemd[1]: Started CUPS Scheduler.
Nov 26 04:03:21 pixel-MS-7369 systemd[1]: Reloading.
Nov 26 04:03:22 pixel-MS-7369 systemd[1]: snapd.refresh.timer: Adding 3h 7min 13.593699s random time.
Nov 26 04:03:22 pixel-MS-7369 systemd[1]: apt-daily.timer: Adding 5h 59min 47.720147s random time.
Nov 26 04:03:22 pixel-MS-7369 systemd[1]: Started ACPI event daemon.
Nov 26 04:03:22 pixel-MS-7369 systemd[1]: Started CUPS Scheduler.
Nov 26 04:03:22 pixel-MS-7369 systemd[1]: Mounting Mount unit for darktable-kyrofa...
Nov 26 04:03:22 pixel-MS-7369 systemd[1]: Mounted Mount unit for darktable-kyrofa.
Nov 26 04:03:22 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2760 on Do: Copy snap "darktable-kyrofa" data
Nov 26 04:03:22 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2761 on Do: Setup snap "darktable-kyrofa" (15) security profiles
Nov 26 04:03:23 pixel-MS-7369 kernel: [ 1825.939886] audit: type=1400 audit(1480125803.274:93): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="snap.darktable-kyrofa.darktable" pid=5259 comm="apparmor_parser"
Nov 26 04:03:23 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2762 on Do: Make snap "darktable-kyrofa" (15) available to the system
Nov 26 04:03:23 pixel-MS-7369 gnome-session[2184]: (gnome-software:2335): As-WARNING **: failed to rescan: Failed to parse /var/lib/snapd/desktop/applications/darktable-kyrofa_darktable.desktop file: cannot process file of type application/x-desktop
Nov 26 04:03:23 pixel-MS-7369 /usr/lib/snapd/snapd[862]: desktop.go:178: DEBUG: update-desktop-database successful
Nov 26 04:03:23 pixel-MS-7369 /usr/lib/snapd/snapd[862]: taskrunner.go:353: DEBUG: Running task 2763 on Do: Start snap "darktable-kyrofa" (15) services
Nov 26 04:03:23 pixel-MS-7369 /usr/lib/snapd/snapd[862]: daemon.go:174: DEBUG: uid=1001;@ GET /v2/snaps 5.946041ms 200
Nov 26 04:03:27 pixel-MS-7369 gnome-session[2184]: (gnome-software:2335): Gs-WARNING **: failed to get updates: no results to show
Nov 26 04:03:28 pixel-MS-7369 /usr/lib/snapd/snapd[862]: daemon.go:174: DEBUG: uid=1001;@ GET /v2/snaps 17.295342ms 200
Nov 26 04:03:39 pixel-MS-7369 /usr/lib/snapd/snapd[862]: daemon.go:174: DEBUG: uid=1001;@ GET /v2/snaps 6.019233ms 200
Nov 26 04:04:03 pixel-MS-7369 kernel: [ 1866.113887] audit: type=1400 audit(1480125843.452:94): apparmor="DENIED" operation="open" profile="snap.darktable-kyrofa.darktable" name="/usr/share/glib-2.0/schemas/" pid=5310 comm="desktop-launch" requested_mask="r" denied_mask="r" fsuid=1001 ouid=0
Nov 26 04:04:05 pixel-MS-7369 kernel: [ 1868.031028] traps: darktable[5272] trap invalid opcode ip:7f69c91a88e7 sp:7ffcda6f4d40 error:0 in libdarktable.so[7f69c9139000+24d000]

**Comment by pixelr0** [comment]
[ 1478.597293] traps: darktable[4974] trap invalid opcode ip:7ff824f9b5bf sp:7ffd91446a80 error:0 in libdarktable.so[7ff824f1f000+276000]

**Comment by pixelr0** [comment]
darktable-kyrofa (stable) 2.0.7snap3 from 'kyrofa' installed
~$ darktable-kyrofa.darktable 
Illegal instruction (core dumped)

new install on a fresh ubuntu 16.04.1 image + overlay ppa, using an intel sandy bridge this time

same core dump

**Comment by pixelr0** [comment]
~$ snap --version
snap    2.17.1ubuntu1
snapd   2.17.1ubuntu1
series  16
ubuntu  16.04

**Comment by huaracheguarache** [comment]
It seems like I have this issue as well:

```
~$ darktable-kyrofa.darktable
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Illegal instruction (core dumped)
```

Currently running: Ubuntu 16.04 with version 2.2.5snap2. 

I'm pretty inexperienced with debugging, and I would appreciate if you could tell me what I should run to give you the logs you need.

**Comment by kyrofa** [comment]
I think I FINALLY figured this out: the `BINARY_PACKAGE_BUILD` param in darktable.

**Comment by kyrofa** [comment]
Yeah, check the `edge` channel, seems to be fixed there.

**Comment by pixelr0** [comment]
yep, works fine now. thanks! o/
